### ISSUE TITLE
Science Logic

### ISSUE THREAD

**Issue by TurboMair** [TurboMair/nwmsusoftprac#5]
The system in place for checking if the polyatomic compounds (anion) the player selects is the correct answer to cause a precipitate reaction with the ionized solution in the puddle. There can either be done with a manual dictionary of every compound and solution pair, or possibly a solubility table dictionary that can check almost all combinations.

**Comment by DopeAnt25** [comment]
- started research to find out what the puddles are made of and to figgure out what the flask are going to contain
