### ISSUE TITLE
Dolphin Scripts

### ISSUE THREAD

**Issue by TurboMair** [TurboMair/nwmsusoftprac#6]
The dolphin is the helper in the game. There should be a bunch of dialogue made that will guide the player through how to play the game, as well as subtle hints to the solution of the current issue. As well as the dialogue script, there should be a text box system that will work along side the HUD to display the text as well as play a dolphin sound.

**Comment by julaij** [comment]
Researched the solubility rules and developed sample dolphin prompts. I have opened a PR with the sample prompts and valuable research in a word document.

**Comment by TurboMair** [comment]
a function that till accept 2 values. One for level difficulty and one for the current puddles content. 
The function will need to 
- Turn on visibility of the "Dolphin" node, showing the empty textbox, textbox outline, and dolphin image. (Waiting for official dolphin image, but you may use a placeholder)
- Play a dolphin sound to mimic speaking
- Select the correct dialogue option from a database of options (This can be done with a dictionary, a json file, or whatever you prefer)

There will also need to be a function that will close the textbox when an "X" button is pressed in the top right corner.
The function will need to
- Clear the text box's content
- Hide the sprites for the textbox outline, dolphin, and textbox

There will need to be the data base itself that is filled dialogue options for the dolphin to speak with the player. These are creatively lenient, and should guide the player to the correct answer. Work with Anthony and the documentation for how to approach each different problem
